RULE_ORDER = ("NBA-000", "NBA-100", "NBA-110", "NBA-200", "NBA-210", "NBA-220", "NBA-230", "NBA-240", "NBA-300", "NBA-310", "NBA-400", "NBA-900", "NBA-910", "NBA-920")

RULE_META = {
    "NBA-000": ("P0", "HARD_SUPPRESSED", "WAIT", "NONE", "INFORMATION_COLLECTION"),
    "NBA-100": ("P1", "CALLBACK_DUE", "CALLBACK", "CALL", "CALLBACK"),
    "NBA-110": ("P2", "INVALID_CONTACT", "VERIFY_CONTACT", "NONE", "CONTACT_VERIFICATION"),
    "NBA-200": ("P3", "PARTIAL_PTP", "PARTIAL_PAYMENT", "CALL", "PAYMENT"),
    "NBA-210": ("P4", "BROKEN_PTP_RECENT_INFLOW", "PTP_RECOVERY", "CALL", "PAYMENT"),
    "NBA-220": ("P4", "BROKEN_PTP", "CONTACT", "CALL", "PAYMENT"),
    "NBA-230": ("P5", "OPEN_PTP", "PTP_FOLLOW_UP", "CALL", "PTP_KEEP"),
    "NBA-240": ("P6", "KEPT_PTP", "WAIT", "NONE", "PTP_KEEP"),
    "NBA-300": ("P7", "CALL_SELF_CURE", "WAIT_SELF_CURE", "NONE", "PAYMENT"),
    "NBA-310": ("P7", "CBS_SELF_CURE", "WAIT", "NONE", "PAYMENT"),
    "NBA-400": ("P8", "RTP_ESCALATION", "ESCALATE", "CALL", "PAYMENT"),
    "NBA-900": ("P9", "CALL_DEFAULT", "CONTACT", "CALL", "PAYMENT"),
    "NBA-910": ("P9", "CBS_DEFAULT", "REMIND", "SMS", "PAYMENT"),
    "NBA-920": ("P9", "OTHER_DEFAULT", "WAIT", "NONE", "INFORMATION_COLLECTION"),
}
