import { FormEvent, useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Database, ExternalLink, Layers3, LoaderCircle, LogIn, LogOut, MessageCircle, Play, ShieldCheck, Sparkles, Target, X, Zap } from 'lucide-react';

const storyAssets = '/landing-story/';
const demoScenes = [
  ['Bài toán ưu tiên', 'slide2.png', 'Bối cảnh: nhiều tín hiệu, một câu hỏi cần trả lời hôm nay.'],
  ['Các tín hiệu dữ liệu', 'slide6.png', 'Dữ liệu được đặt trong cùng một bức tranh nghiệp vụ.'],
  ['Từ dữ liệu đến hành động', 'slide4.png', 'Decision Core — Bộ máy quyết định nghiệp vụ — chuyển dữ liệu thành kết quả có thể giải thích.'],
  ['Danh sách ưu tiên', 'slide7.png', 'Cán bộ bắt đầu từ danh sách hồ sơ nên được xem xét trước.'],
  ['Hồ sơ SYN002846', 'slide8.png', 'Một hồ sơ cụ thể, với dòng tiền, cam kết và lịch sử liên hệ.'],
  ['Điểm cơ hội thu hồi', 'slide9.png', '47/100 là điểm ưu tiên tương đối, không phải xác suất thanh toán.'],
  ['Bằng chứng quyết định', 'slide10.png', 'Các tín hiệu phía sau đề xuất được trình bày để cán bộ kiểm tra.'],
  ['Hỏi vì sao chưa nên gọi', 'slide11.png', 'Trợ lý giải thích dựa trên kết quả đã được Bộ máy quyết định xác định.'],
  ['Mô phỏng tiền vào = 0', 'slide12.png', 'Một giả định mới làm thay đổi bối cảnh, không thay đổi dữ liệu thật.'],
  ['Hành động thay đổi', 'slide13.png', 'Bối cảnh mới dẫn tới hành động và kênh xử lý mới.'],
  ['Tính điểm qua Zalo', 'zalo-demo-live-context.png', 'Minh họa Zalo giữ hồ sơ SYN002846 trong suốt cuộc trò chuyện.'],
  ['Hỏi mô phỏng qua Zalo', 'zalo-demo-live-context.png', 'Câu hỏi tự nhiên vẫn bám theo trạng thái mô phỏng vừa tạo.'],
  ['Thế giờ làm gì', 'zalo-demo-live-context.png', 'Follow-up trả lời theo after-state, không quay về trạng thái ban đầu.'],
  ['Tác động và thông điệp cuối', 'slide14.png', 'Tác động được trình bày như ước tính theo giả định của bản demo.'],
] as const;

function StoryImage({ src, alt, className = '' }: { src: string; alt: string; className?: string }) {
  return <a className={`story-image ${className}`} href={`${storyAssets}${src}`} target="_blank" rel="noreferrer">
    <img src={`${storyAssets}${src}`} alt={alt} loading="lazy" />
    <span className="image-expand"><ExternalLink size={14} /> Mở ảnh lớn</span>
  </a>;
}

function SectionHeading({ eyebrow, title, children, light = false }: { eyebrow: string; title: string; children?: React.ReactNode; light?: boolean }) {
  return <div className={`story-heading ${light ? 'story-heading-light' : ''}`}><span className="story-eyebrow">{eyebrow}</span><h2>{title}</h2>{children && <p>{children}</p>}</div>;
}

function DemoGallery() {
  const [open, setOpen] = useState<number | null>(null);
  const move = (delta: number) => setOpen(current => current === null ? 0 : (current + delta + demoScenes.length) % demoScenes.length);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (open === null) return; if (event.key === 'Escape') setOpen(null); if (event.key === 'ArrowRight') move(1); if (event.key === 'ArrowLeft') move(-1); }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [open]);
  return <>
    <div className="demo-feature-grid">{[0, 2, 5, 8, 10, 13].map(index => <button className="demo-feature" key={index} onClick={() => setOpen(index)}><img src={`${storyAssets}${demoScenes[index][1]}`} alt="" /><span><b>{demoScenes[index][0]}</b><small>{demoScenes[index][2]}</small></span><Play size={18} /></button>)}</div>
    <button className="story-button story-button-outline" onClick={() => setOpen(0)}>Xem toàn bộ hành trình demo <ArrowRight size={17} /></button>
    {open !== null && <div className="gallery-backdrop" role="dialog" aria-modal="true" aria-label="Hành trình demo" onClick={() => setOpen(null)}><div className="gallery-modal" onClick={e => e.stopPropagation()}><div className="gallery-toolbar"><span>{open + 1} / {demoScenes.length}</span><button aria-label="Đóng gallery" onClick={() => setOpen(null)}><X size={20} /></button></div><img src={`${storyAssets}${demoScenes[open][1]}`} alt={demoScenes[open][0]} /><div className="gallery-caption"><div><b>{demoScenes[open][0]}</b><p>{demoScenes[open][2]} <em>Ảnh minh họa theo kịch bản demo.</em></p></div><div className="gallery-controls"><button aria-label="Cảnh trước" onClick={() => move(-1)}><ChevronLeft /></button><button aria-label="Cảnh tiếp theo" onClick={() => move(1)}><ChevronRight /></button></div></div></div></div>}
  </>;
}

function Faq() { const [open, setOpen] = useState<number | null>(null); const items = [
  ['Quy tắc đã quyết định rồi, AI để làm gì?', 'AI giúp hiểu câu hỏi tự nhiên, tóm tắt, giải thích và tra cứu kiến thức. Kết quả nghiệp vụ vẫn do Bộ máy quyết định xác định.'],
  ['Đây có phải chatbot gắn quy tắc không?', 'Trợ lý là lớp tương tác trên một nền quyết định có căn cứ: câu hỏi về hồ sơ đi theo luồng nghiệp vụ, câu hỏi kiến thức đi theo luồng tra cứu có nguồn.'],
  ['Tại sao không để mô hình ngôn ngữ tự quyết định?', 'Vì chính sách nghiệp vụ cần nhất quán, truy vết và có người chịu trách nhiệm. Mô hình hỗ trợ hiểu và giải thích, không thay thế quyền nghiệp vụ.'],
  ['GreenNode được dùng thật ở đâu?', 'GreenNode hỗ trợ hiểu câu hỏi, diễn giải, tra cứu kiến thức và năng lực điều phối đã được kiểm chứng. Bộ máy quyết định vẫn giữ quyền xác định tuyến, điểm, hành động và kênh.'],
  ['Điểm 47 có phải xác suất thanh toán 47% không?', 'Không. Recovery Opportunity — Điểm cơ hội thu hồi — là điểm ưu tiên tương đối để so sánh hồ sơ, không phải xác suất khách hàng sẽ thanh toán.'],
  ['32 hồ sơ có nghĩa là giảm 32 cuộc gọi không?', 'Không. Đây là số hồ sơ thuộc tuyến gọi nhưng trong giả định demo hiện chưa cần gọi ngay; chưa thể quy đổi thành số cuộc gọi đã giảm.'],
]; return <div className="faq-list">{items.map(([q, a], i) => <div className="faq-item" key={q}><button onClick={() => setOpen(open === i ? null : i)} aria-expanded={open === i}><span><CircleHelp size={18} />{q}</span>{open === i ? <ChevronDown /> : <ChevronRight />}</button>{open === i && <p>{a}</p>}</div>)}</div>; }

export function PublicLanding() {
  useEffect(() => {
    if (window.location.pathname === '/gioi-thieu') window.history.replaceState({}, '', '/');
  }, []);
  const goLogin = () => { window.location.href = '/login'; };
  return <div className="public-site">
    <header className="public-header"><a className="public-brand" href="/" aria-label="MSB Trợ lý Thu hồi Nợ"><span className="public-brand-mark">MSB</span><span><b>Trợ lý Thu hồi Nợ</b><small>Powered by GreenNode AI</small></span></a><nav className="story-nav" aria-label="Điều hướng landing"><a href="#problem">Bài toán</a><a href="#solution">Giải pháp</a><a href="#demo">Demo</a><a href="#channels">Web + Zalo</a><a href="#architecture">Cách hoạt động</a><a href="#impact">Tác động</a><a href="#faq">FAQ</a><a className="public-login-link" href="/login"><LogIn size={15}/> Trải nghiệm</a></nav></header>
    <main>
      <section className="story-hero"><div className="story-hero-copy"><span className="story-kicker">MSB AI Hackathon 2026 · AI for My Team — AI cho đội ngũ</span><h1>Không tìm khách hàng nợ nhiều nhất.<br /><span>Tìm cơ hội thu hồi tốt nhất tiếp theo.</span></h1><p>MSB Trợ lý Thu hồi Nợ giúp cán bộ ưu tiên đúng hồ sơ, hiểu vì sao hệ thống đề xuất hành động, mô phỏng thay đổi và hỏi nhanh trên Web hoặc Zalo.</p><div className="hero-points"><span>Đúng khách hàng</span><span>Đúng hành động</span><span>Đúng thời điểm</span></div><div className="story-actions"><a className="story-button story-button-primary" href="/login">Trải nghiệm bản demo <ArrowRight size={17} /></a><a className="story-button story-button-quiet" href="#demo">Xem hành trình demo</a></div><p className="story-notice"><ShieldCheck size={16} /> Bản demo dùng dữ liệu mô phỏng, không sử dụng dữ liệu khách hàng thật.</p></div><div className="hero-visual"><div className="hero-orbit"><Target size={30} /><span>Ưu tiên theo<br /><b>cơ hội thu hồi</b></span></div><div className="hero-score"><small>HỒ SƠ ĐANG XEM XÉT</small><b>SYN002846</b><strong>47<small>/100</small></strong><span>Chờ khách hàng tự thanh toán</span></div><div className="hero-spark"><Sparkles size={22} /> Lý do rõ ràng</div></div></section>
      <section className="story-quick"><span>Muốn xem nhanh?</span><a href="#demo">Xem hành trình demo trong khoảng 3 phút <ArrowRight size={15} /></a><span>Muốn xem kỹ?</span><a href="#architecture">Khám phá cách hệ thống hoạt động <ArrowRight size={15} /></a></section>
      <section className="story-section story-problem" id="problem"><SectionHeading eyebrow="BÀI TOÁN" title="Cán bộ không thiếu dữ liệu. Điểm khó là biến dữ liệu thành hành động hôm nay." children="Dư nợ lớn chưa chắc nên gọi trước. Ngày quá hạn chưa phản ánh hết khả năng tự thanh toán. Cán bộ phải kết hợp dòng tiền, cam kết thanh toán, lịch sử liên hệ và thời điểm." /><div className="problem-layout"><StoryImage src="slide2.png" alt="Minh họa bài toán biến danh sách nợ thành quyết định hành động" /><div className="problem-signals"><div><b>01</b><h3>Dư nợ lớn ≠ nên gọi trước</h3><p>Thứ tự nhìn thấy trên danh sách chưa chắc là cơ hội thu hồi tốt nhất.</p></div><div><b>02</b><h3>Một quyết định cần nhiều tín hiệu</h3><p>Dòng tiền, cam kết, khả năng liên hệ và thời điểm cần được nhìn cùng nhau.</p></div><div><b>03</b><h3>Cần biết “vì sao”</h3><p>Cán bộ và quản lý cần một lời giải thích có căn cứ để hành động tự tin.</p></div></div></div><p className="story-quote">Bài toán không chỉ là ai nợ nhiều, mà là hôm nay nên ưu tiên ai, làm gì và vì sao.</p></section>
      <section className="story-section story-solution" id="solution"><SectionHeading eyebrow="GIẢI PHÁP" title="Một Trợ lý giúp biến dữ liệu thành quyết định có căn cứ" children="Một nền tảng để cán bộ đi từ ưu tiên hồ sơ đến hành động, với bằng chứng và mô phỏng ngay trong cùng một câu chuyện." /><div className="solution-grid"><div className="solution-lead"><Zap size={26} /><b>Recovery Opportunity</b><h3>Không phải ai nợ nhiều nhất, mà là ai có cơ hội thu hồi tốt nhất tiếp theo.</h3><p>Điểm ưu tiên tương đối giúp sắp xếp sự chú ý của đội ngũ theo bối cảnh hiện tại.</p></div>{[['Ưu tiên hồ sơ','Biết nên xem ai trước',Target],['Giải thích quyết định','Hiểu dữ liệu phía sau đề xuất',MessageCircle],['Mô phỏng tình huống','Thử thay đổi bối cảnh an toàn',Sparkles],['Tra cứu kiến thức có nguồn','Hỏi nhanh, có căn cứ',Database]].map(([title, text, Icon]) => <div className="solution-card" key={title as string}><Icon size={23} /><b>{title as string}</b><p>{text as string}</p></div>)}</div></section>
      <section className="story-section channels-section" id="channels"><div className="channel-copy"><SectionHeading eyebrow="WEB + ZALO" title="Xem sâu trên Web. Hỏi nhanh qua Zalo." children="Hai kênh khác nhau, cùng một bộ máy quyết định." /><div className="channel-list"><div><span className="channel-icon web">W</span><p><b>Web</b><small>Danh sách ưu tiên, hồ sơ, bằng chứng, điểm, mô phỏng và Trợ lý.</small></p></div><div><span className="channel-icon zalo">Z</span><p><b>Zalo</b><small>Hỏi tự nhiên, giữ ngữ cảnh hồ sơ và follow-up theo mô phỏng.</small></p></div></div><div className="chat-bubbles"><span>Tính điểm SYN002846</span><span>Nếu nó không có tiền vào tuần này thì sao?</span><span>Thế giờ làm gì?</span></div></div><StoryImage src="zalo-demo-live-context.png" alt="Demo Zalo thực tế với hồ sơ SYN002846 và ngữ cảnh mô phỏng" /></section>
      <section className="story-section journey-section" id="journey"><SectionHeading eyebrow="HÀNH TRÌNH NGƯỜI DÙNG" title="Từ trang giới thiệu → bằng chứng → hành động" children="Trang giới thiệu (Landing — trang giới thiệu) mở đầu cho một hành trình thống nhất trên Web hoặc Zalo." /><StoryImage src="user-journey.png" alt="Infographic hành trình người dùng từ trang giới thiệu đến hành động" className="wide-image" /><p className="image-summary"><CheckCircle2 size={17} /> Sáu bước nối liền: hiểu bài toán → đăng nhập → danh sách ưu tiên → hồ sơ → hỏi Trợ lý → hành động, mô phỏng hoặc tác động dự kiến.</p></section>
      <section className="story-section demo-section" id="demo"><SectionHeading eyebrow="TRÌNH DIỄN SẢN PHẨM" title="Theo một hồ sơ từ dữ liệu đến hành động" children="Chọn một cảnh để xem lại câu chuyện demo. Các hình ảnh minh họa theo kịch bản; dữ liệu là dữ liệu mô phỏng." /><DemoGallery /></section>
      <section className="story-section case-section" id="case"><div className="case-copy"><SectionHeading eyebrow="TÌNH HUỐNG DEMO" title="Thuộc tuyến gọi không có nghĩa hôm nay nhất thiết phải gọi" children="SYN002846 cho thấy sự khác nhau giữa tuyến xử lý và hành động phù hợp tại thời điểm hiện tại." /><div className="case-action"><span>Tuyến CALL — tuyến gọi</span><b>Chờ khách hàng tự thanh toán</b><small>Kênh: Chưa cần liên hệ</small></div></div><div className="case-facts">{[['Quá hạn','11 ngày'],['Tiền vào 7 ngày','48 triệu đồng'],['Dòng tiền ròng 30 ngày','168 triệu đồng'],['Cam kết thanh toán','Chưa có'],['Điểm cơ hội thu hồi','47 / 100']].map(([l,v]) => <div key={l}><span>{l}</span><b>{v}</b></div>)}</div></section>
      <section className="story-section score-section" id="score"><div className="score-intro"><SectionHeading eyebrow="MINH BẠCH" title="Không chỉ trả lời “làm gì”, hệ thống còn cho biết “vì sao”" children="Recovery Opportunity — Điểm cơ hội thu hồi — được cấu thành từ các tín hiệu nghiệp vụ có thể xem lại." /><div className="score-total"><strong>47</strong><span>/ 100</span><small>Điểm ưu tiên tương đối</small></div></div><div className="breakdown-grid">{[['Mức khẩn cấp nghiệp vụ','8 / 20'],['Khả năng thanh toán','20 / 25'],['Mức sẵn sàng thanh toán','4 / 20'],['Khả năng liên hệ','11 / 15'],['Cơ hội theo thời điểm','4 / 15'],['Điều chỉnh chiến lược','0 / 5']].map(([l,v]) => <div key={l}><span>{l}</span><b>{v}</b><i style={{ width: `${parseInt(v) / parseInt(v.split('/')[1]) * 100}%` }} /></div>)}</div><p className="disclaimer">Điểm cơ hội thu hồi là điểm ưu tiên tương đối, không phải xác suất khách hàng sẽ thanh toán.</p></section>
      <section className="story-section simulation-section" id="simulation"><SectionHeading eyebrow="MÔ PHỎNG TÌNH HUỐNG" title="Cùng một chính sách, bối cảnh thay đổi thì hành động có thể thay đổi" children="What-if Simulation — mô phỏng tình huống giả định — giúp cán bộ nhìn thấy tác động của một tín hiệu mới." /><div className="sim-grid"><div><span>TRƯỚC</span><b>48 triệu đồng vào 7 ngày</b><strong>Chờ khách hàng tự thanh toán</strong><small>Chưa cần liên hệ</small></div><ArrowRight /><div className="sim-after"><span>GIẢ ĐỊNH</span><b>0 đồng vào 7 ngày</b><strong>Liên hệ khách hàng</strong><small>Gọi điện</small></div></div><p className="disclaimer">Mô phỏng không thay đổi dữ liệu thật.</p></section>
      <section className="story-section visual-anchor-section"><div><SectionHeading eyebrow="HAI LUỒNG TRỢ LÝ" title="Đúng luồng cho đúng câu hỏi" children="Câu hỏi về khách hàng đi theo luồng nghiệp vụ; câu hỏi về tri thức đi theo luồng tra cứu có nguồn tham khảo." /><p className="image-summary"><ShieldCheck size={18} /> Câu hỏi nghiệp vụ: Bộ máy quyết định giữ quyền xác định kết quả.</p><p className="image-summary"><Database size={18} /> Câu hỏi kiến thức: RAG — tra cứu tăng cường bằng dữ liệu — cung cấp kiến thức có nguồn.</p></div><StoryImage src="two-assistant-flows.png" alt="Infographic hai luồng Trợ lý: quyết định nghiệp vụ và tra cứu kiến thức" /></section>
      <section className="story-section architecture-section" id="architecture"><SectionHeading eyebrow="CÁCH HỆ THỐNG HOẠT ĐỘNG" title="Web và Zalo dùng chung một bộ máy quyết định" children="Kênh tương tác có thể khác nhau; nền tảng dữ liệu, luật nghiệp vụ, điểm ưu tiên và hành động đề xuất cùng đi qua một nền tảng quyết định." /><StoryImage src="system-architecture.png" alt="Infographic kiến trúc Web, Zalo, Decision Core và GreenNode" className="wide-image" /><div className="architecture-notes"><span>Web / Zalo: kênh tương tác</span><span>Decision Core: Bộ máy quyết định nghiệp vụ</span><span>GreenNode AI: hiểu, tra cứu, diễn giải</span><span>Nhúng ngôn ngữ đa ngôn ngữ chạy cục bộ</span></div></section>
      <section className="story-section green-section" id="greennode"><div className="green-copy"><SectionHeading eyebrow="GREENNODE TRONG SẢN PHẨM" title="GreenNode giúp Trợ lý hiểu, tra cứu và giải thích" children="GreenNode mở rộng khả năng trợ lý; Decision Core — Bộ máy quyết định nghiệp vụ — vẫn giữ quyền quyết định." /><div className="green-points"><div><b>GreenNode MaaS + GLM 5.2</b><span>Hiểu câu hỏi tự nhiên, diễn giải kết quả và hỗ trợ giải thích/mô phỏng.</span></div><div><b>Vector Database + Qwen Flash</b><span>Tra cứu kiến thức có nguồn, tổng hợp câu trả lời từ tài liệu; không quyết định nghiệp vụ.</span></div><div><b>AgentBase</b><span>Năng lực điều phối công cụ đã được kiểm chứng; không phải nơi ra quyết định.</span></div><div><b>Local multilingual embedding</b><span>Nhúng đa ngôn ngữ chạy cục bộ, nằm ngoài GreenNode.</span></div></div></div><StoryImage src="greennode-in-product.png" alt="GreenNode trong sản phẩm, phân biệt quyền Decision Core và năng lực AI hỗ trợ" /></section>
      <section className="story-section control-section" id="control"><SectionHeading eyebrow="AI CÓ KIỂM SOÁT" title="AI hỗ trợ cán bộ, không thay thế quyền quyết định nghiệp vụ" /><div className="control-grid"><div><span>AI hỗ trợ</span><ul>{['Hiểu câu hỏi','Giải thích và tóm tắt','Tra cứu kiến thức có nguồn','Giao tiếp trên Web / Zalo'].map(x => <li key={x}><CheckCircle2 size={17} />{x}</li>)}</ul></div><div><span>Bộ máy quyết định</span><ul>{['Phân tuyến','Tính điểm','Xác định hành động','Xác định kênh và mô phỏng'].map(x => <li key={x}><ShieldCheck size={17} />{x}</li>)}</ul></div></div><p className="story-quote">AI hỗ trợ hiểu, giải thích và tra cứu; Bộ máy quyết định giữ quyền xác định kết quả nghiệp vụ.</p></section>
      <section className="story-section impact-section" id="impact"><SectionHeading eyebrow="TÁC ĐỘNG DỰ KIẾN" title="Ưu tiên tốt hơn có thể giảm thao tác không cần thiết" children="Các con số dưới đây là quy mô minh họa cho bản demo, không phải kết quả tài chính đã đạt." /><div className="impact-stats"><div><b>3.000</b><span>hồ sơ demo</span></div><div><b>1.740</b><span>thuộc tuyến gọi</span></div><div><b>32</b><span>thuộc tuyến gọi nhưng hiện chưa cần gọi ngay</span></div><div><b>~1.065</b><span>giờ/năm</span></div><div><b>~106,5 triệu</b><span>đồng/năm</span></div></div><p className="disclaimer">Ước tính theo giả định của bản demo, không phải ROI đã đạt. 32 hồ sơ không đồng nghĩa đã giảm được 32 cuộc gọi.</p></section>
      <section className="story-section judge-section" id="judge"><SectionHeading eyebrow="TÓM TẮT CHO BAN GIÁM KHẢO" title="Nếu chỉ có một phút để xem lại sản phẩm" /><div className="judge-grid"><div><b>Bài toán</b><p>Khó xác định hồ sơ nào nên ưu tiên hôm nay.</p></div><div><b>Giải pháp</b><p>Trợ lý Thu hồi Nợ trên Web và Zalo.</p></div><div><b>Khác biệt</b><p>Ưu tiên theo cơ hội thu hồi, không chỉ dư nợ hay ngày quá hạn.</p></div><div><b>AI & kiểm soát</b><p>AI hỗ trợ hiểu, giải thích, tra cứu; Decision Core giữ quyền nghiệp vụ.</p></div><div><b>Demo</b><p>Dữ liệu mô phỏng, không dùng dữ liệu khách hàng thật.</p></div></div></section>
      <section className="story-section faq-section" id="faq"><SectionHeading eyebrow="CÂU HỎI THƯỜNG GẶP" title="Những câu hỏi quan trọng, trả lời thẳng" /><Faq /></section>
      <section className="story-section roadmap-section" id="roadmap"><SectionHeading eyebrow="LỘ TRÌNH" title="Bắt đầu từ nền tảng quyết định có thể kiểm chứng" /><div className="roadmap-grid"><div><span>HIỆN TẠI</span><ul>{['Web','Zalo','Decision Core','Mô phỏng','Knowledge RAG — tra cứu có nguồn','Dữ liệu mô phỏng'].map(x => <li key={x}><CheckCircle2 size={16} />{x}</li>)}</ul></div><div><span>TIẾP THEO · HƯỚNG PHÁT TRIỂN TƯƠNG LAI</span><ul>{['T24','DigiLenO','Contact Center','Đo lường hiệu quả','Mở rộng kênh','AI hỗ trợ gọi điện trong tương lai'].map(x => <li key={x}><ArrowRight size={16} />{x}</li>)}</ul></div></div><p className="disclaimer">Các nội dung “tiếp theo” là hướng phát triển tương lai, chưa phải tính năng đã triển khai. Không bao gồm gọi điện tự động.</p></section>
    </main><footer className="story-footer"><div><span className="story-kicker">MSB AI Hackathon 2026</span><h2>Từ dữ liệu hôm nay đến hành động hiệu quả hơn</h2><p>MSB Trợ lý Thu hồi Nợ giúp cán bộ ưu tiên đúng hồ sơ, hiểu rõ lý do và hành động có căn cứ.</p><a className="story-button story-button-primary" href="/login">Bắt đầu trải nghiệm <ArrowRight size={17} /></a></div><div className="footer-meta"><b>Debt Radar</b><span>Powered by GreenNode AI — vận hành cùng nền tảng AI GreenNode</span><small>Dữ liệu mô phỏng · Không sử dụng dữ liệu khách hàng thật</small></div></footer>
  </div>;
}

export function LoginPage() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { fetch('/demo/auth/me', { credentials: 'include' }).then(r => { if (r.ok) window.location.replace('/app'); }); }, []);
  const submit = async (event: FormEvent) => {
    event.preventDefault(); if (busy) return; setBusy(true); setError('');
    try {
      const response = await fetch('/demo/auth/login', { method: 'POST', credentials: 'include', headers: {'Content-Type':'application/json'}, body: JSON.stringify({username, password}) });
      const body = await response.json();
      if (!response.ok) throw new Error(body?.error?.message || 'Không thể đăng nhập.');
      const next = new URLSearchParams(window.location.search).get('next');
      window.location.replace(next && next.startsWith('/app') ? next : '/app');
    } catch (e: any) { setError(e.message || 'Không thể đăng nhập.'); setBusy(false); }
  };
  return <main className="login-page">
    <a className="login-brand" href="/"><span className="public-brand-mark">MSB</span><span><b>Trợ lý Thu hồi Nợ</b><small>Powered by GreenNode AI</small></span></a>
    <section className="login-card" aria-labelledby="login-title">
      <div className="login-icon"><ShieldCheck size={21}/></div><div className="eyebrow">KHU VỰC TÁC NGHIỆP</div>
      <h1 id="login-title">Đăng nhập hệ thống</h1><p>Truy cập Tổng quan, danh sách ưu tiên và hồ sơ khách hàng trong bản demo.</p>
      <form onSubmit={submit}><label>Tên đăng nhập<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required /></label><label>Mật khẩu<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required /></label>{error&&<p className="login-error" role="alert">{error}</p>}<button className="primary login-submit" disabled={busy}>{busy?<><LoaderCircle className="spin" size={16}/> Đang đăng nhập...</>:<>Đăng nhập <ArrowRight size={16}/></>}</button></form>
      <small className="login-disclaimer">Đây là quyền truy cập bản demo, không phải xác thực ngân hàng trong môi trường sản xuất.</small>
    </section>
    <footer className="login-footer">MSB · Powered by GreenNode AI · Dữ liệu mô phỏng</footer>
  </main>;
}

export function LogoutButton({logout}:{logout:()=>void}) { return <button className="logout-button" onClick={logout}><LogOut size={16}/> Đăng xuất</button>; }
