import { FormEvent, useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Database, ExternalLink, Layers3, LoaderCircle, LogIn, LogOut, MessageCircle, Play, ShieldCheck, Sparkles, Target, X, Zap } from 'lucide-react';

const storyAssets = '/landing-story/';
const demoScenes = [
  ['Bài toán ưu tiên', 'slide2.png', 'Bối cảnh: nhiều tín hiệu, một câu hỏi cần trả lời hôm nay.'],
  ['Các tín hiệu dữ liệu', 'slide6.png', 'Dữ liệu được đặt trong cùng một bức tranh nghiệp vụ.'],
  ['Từ dữ liệu đến hành động', 'slide4.png', 'Decision Core — Bộ máy quyết định nghiệp vụ — chuyển dữ liệu thành kết quả có thể giải thích.'],
  ['Danh sách ưu tiên', 'slide7.png', 'Cán bộ bắt đầu từ danh sách hồ sơ nên được xem xét trước.'],
  ['Hồ sơ SYN002846', 'slide8.png', 'Một hồ sơ cụ thể, với dòng tiền, cam kết và lịch sử liên hệ.'],
  ['Điểm cơ hội thu hồi', 'slide9.png', '47/100 là điểm ưu tiên tương đối, không phải xác suất thanh toán.'],
  ['Bằng chứng quyết định', 'slide10.png', 'Các tín hiệu phía sau đề xuất được trình bày để cán bộ kiểm tra.'],
  ['Hỏi vì sao chưa nên gọi', 'slide11.png', 'Trợ lý giải thích dựa trên kết quả đã được Bộ máy quyết định xác định.'],
  ['Mô phỏng tiền vào = 0', 'slide12.png', 'Một giả định mới làm thay đổi bối cảnh, không thay đổi dữ liệu thật.'],
  ['Hành động thay đổi', 'slide13.png', 'Bối cảnh mới dẫn tới hành động và kênh xử lý mới.'],
  ['Tính điểm qua Zalo', 'zalo-demo-live-context.png', 'Minh họa Zalo giữ hồ sơ SYN002846 trong suốt cuộc trò chuyện.'],
  ['Hỏi mô phỏng qua Zalo', 'zalo-demo-live-context.png', 'Câu hỏi tự nhiên vẫn bám theo trạng thái mô phỏng vừa tạo.'],
  ['Thế giờ làm gì', 'zalo-demo-live-context.png', 'Follow-up trả lời theo after-state, không quay về trạng thái ban đầu.'],
  ['Tác động và thông điệp cuối', 'slide14.png', 'Tác động được trình bày như ước tính theo giả định của bản demo.'],
] as const;

function StoryImage({ src, alt, className = '' }: { src: string; alt: string; className?: string }) {
  return <a className={`story-image ${className}`} href={`${storyAssets}${src}`} target="_blank" rel="noreferrer">
    <img src={`${storyAssets}${src}`} alt={alt} loading="lazy" />
    <span className="image-expand"><ExternalLink size={14} /> Mở ảnh lớn</span>
  </a>;
}

function SectionHeading({ eyebrow, title, children, light = false }: { eyebrow: string; title: string; children?: React.ReactNode; light?: boolean }) {
  return <div className={`story-heading ${light ? 'story-heading-light' : ''}`}><span className="story-eyebrow">{eyebrow}</span><h2>{title}</h2>{children && <p>{children}</p>}</div>;
}

function DemoGallery() {
  const [open, setOpen] = useState<number | null>(null);
  const move = (delta: number) => setOpen(current => current === null ? 0 : (current + delta + demoScenes.length) % demoScenes.length);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (open === null) return; if (event.key === 'Escape') setOpen(null); if (event.key === 'ArrowRight') move(1); if (event.key === 'ArrowLeft') move(-1); }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [open]);
  return <>
    <div className="demo-feature-grid">{[0, 2, 5, 8, 10, 13].map(index => <button className="demo-feature" key={index} onClick={() => setOpen(index)}><img src={`${storyAssets}${demoScenes[index][1]}`} alt="" /><span><b>{demoScenes[index][0]}</b><small>{demoScenes[index][2]}</small></span><Play size={18} /></button>)}</div>
    <button className="story-button story-button-outline" onClick={() => setOpen(0)}>Xem toàn bộ hành trình demo <ArrowRight size={17} /></button>
    {open !== null && <div className="gallery-backdrop" role="dialog" aria-modal="true" aria-label="Hành trình demo" onClick={() => setOpen(null)}><div className="gallery-modal" onClick={e => e.stopPropagation()}><div className="gallery-toolbar"><span>{open + 1} / {demoScenes.length}</span><button aria-label="Đóng gallery" onClick={() => setOpen(null)}><X size={20} /></button></div><img src={`${storyAssets}${demoScenes[open][1]}`} alt={demoScenes[open][0]} /><div className="gallery-caption"><div><b>{demoScenes[open][0]}</b><p>{demoScenes[open][2]} <em>Ảnh minh họa theo kịch bản demo.</em></p></div><div className="gallery-controls"><button aria-label="Cảnh trước" onClick={() => move(-1)}><ChevronLeft /></button><button aria-label="Cảnh tiếp theo" onClick={() => move(1)}><ChevronRight /></button></div></div></div></div>}
  </>;
}

function Faq() { const [open, setOpen] = useState<number | null>(null); const items = [
  ['Quy tắc đã quyết định rồi, AI để làm gì?', 'AI giúp hiểu câu hỏi tự nhiên, tóm tắt, giải thích và tra cứu kiến thức. Kết quả nghiệp vụ vẫn do Bộ máy quyết định xác định.'],
  ['Đây có phải chatbot gắn quy tắc không?', 'Trợ lý là lớp tương tác trên một nền quyết định có căn cứ: câu hỏi về hồ sơ đi theo luồng nghiệp vụ, câu hỏi kiến thức đi theo luồng tra cứu có nguồn.'],
  ['Tại sao không để mô hình ngôn ngữ tự quyết định?', 'Vì chính sách nghiệp vụ cần nhất quán, truy vết và có người chịu trách nhiệm. Mô hình hỗ trợ hiểu và giải thích, không thay thế quyền nghiệp vụ.'],
  ['GreenNode được dùng thật ở đâu?', 'GreenNode hỗ trợ hiểu câu hỏi, diễn giải, tra cứu kiến thức và năng lực điều phối đã được kiểm chứng. Bộ máy quyết định vẫn giữ quyền xác định tuyến, điểm, hành động và kênh.'],
  ['Điểm 47 có phải xác suất thanh toán 47% không?', 'Không. Recovery Opportunity — Điểm cơ hội thu hồi — là điểm ưu tiên tương đối để so sánh hồ sơ, không phải xác suất khách hàng sẽ thanh toán.'],
  ['32 hồ sơ có nghĩa là giảm 32 cuộc gọi không?', 'Không. Đây là số hồ sơ thuộc tuyến gọi nhưng trong giả định demo hiện chưa cần gọi ngay; chưa thể quy đổi thành số cuộc gọi đã giảm.'],
]; return <div className="faq-list">{items.map(([q, a], i) => <div className="faq-item" key={q}><button onClick={() => setOpen(open === i ? null : i)} aria-expanded={open === i}><span><CircleHelp size={18} />{q}</span>{open === i ? <ChevronDown /> : <ChevronRight />}</button>{open === i && <p>{a}</p>}</div>)}</div>; }

export function PublicLanding() {
  useEffect(() => {
    if (window.location.pathname === '/gioi-thieu') window.history.replaceState({}, '', '/');
  }, []);
  return <div className="public-site">
    <header className="public-header"><div className="story-shell header-shell"><a className="public-brand" href="/" aria-label="MSB Trợ lý Thu hồi Nợ"><span className="public-brand-mark">MSB</span><span><b>Trợ lý Thu hồi Nợ</b><small>Powered by GreenNode AI</small></span></a><nav className="story-nav" aria-label="Điều hướng landing"><a href="#problem">Bài toán</a><a href="#case-brief">AI Case Brief</a><a href="#case">Tình huống</a><a href="#channels">Web + Zalo</a><a href="#greennode">GreenNode</a><a href="#roadmap">Lộ trình</a><a className="public-login-link" href="/login"><LogIn size={15}/> Trải nghiệm</a></nav></div></header>
    <main>
      <section className="story-hero"><div className="story-shell hero-shell"><div className="story-hero-copy"><span className="story-kicker">MSB AI Hackathon 2026 · AI for My Team</span><h1>Không tìm khách hàng nợ nhiều nhất.<br /><span>Tìm cơ hội thu hồi tốt nhất tiếp theo.</span></h1><p>MSB Trợ lý Thu hồi Nợ giúp cán bộ ưu tiên đúng hồ sơ, hiểu lý do, mô phỏng thay đổi và hỏi nhanh trên Web hoặc Zalo.</p><p className="hero-brief"><Sparkles size={17} /> <b>AI Case Brief</b> giúp nắm nhanh tình trạng, bằng chứng quan trọng và lý do của quyết định trên từng hồ sơ.</p><div className="hero-points">{['Đúng khách hàng','Đúng hành động','Đúng thời điểm'].map(point => <span key={point}><CheckCircle2 size={15} />{point}</span>)}</div><div className="story-actions"><a className="story-button story-button-primary" href="/login">Trải nghiệm bản demo <ArrowRight size={17} /></a><a className="story-button story-button-quiet" href="#demo">Xem hành trình demo</a></div><p className="story-notice"><ShieldCheck size={16} /> Bản demo dùng dữ liệu mô phỏng, không sử dụng dữ liệu khách hàng thật.</p><p className="team-line">Nhóm thực hiện: <b>Debt Radar</b></p></div><div className="hero-visual" aria-label="Minh họa hồ sơ ưu tiên SYN002846"><div className="hero-orbit"><Target size={27} /><span>Ưu tiên theo<br /><b>cơ hội thu hồi</b></span></div><div className="hero-score"><small>HỒ SƠ ĐANG XEM XÉT</small><b>SYN002846</b><strong>47<small>/100</small></strong><span>Chờ khách hàng tự thanh toán</span></div><div className="hero-data"><Database size={18} /><span>Dữ liệu và<br /><b>bằng chứng</b></span></div><div className="hero-spark"><Sparkles size={20} /> Lý do rõ ràng</div></div></div></section>
      <section className="story-quick"><div className="story-shell"><span>Muốn xem nhanh?</span><a href="#case-brief">Khám phá AI Case Brief <ArrowRight size={15} /></a><span>Muốn xem kỹ?</span><a href="#demo">Xem hành trình demo <ArrowRight size={15} /></a></div></section>
      <section className="story-section story-problem" id="problem"><SectionHeading eyebrow="01 · BÀI TOÁN" title="Cán bộ không thiếu dữ liệu. Điểm khó là biến dữ liệu thành hành động hôm nay." children="Danh sách dài, dữ liệu rời rạc và kết quả chưa được giải thích khiến việc ưu tiên mỗi ngày trở nên khó khăn." /><div className="problem-layout"><StoryImage src="slide2.png" alt="Minh họa bài toán biến danh sách nợ thành quyết định hành động" /><div className="problem-signals"><div><b>01</b><h3>Danh sách dài</h3><p>Thứ tự chưa phản ánh đầy đủ cơ hội thu hồi.</p></div><div><b>02</b><h3>Hành động hôm nay</h3><p>Thuộc CALL/CBS chưa cho biết ngay cần làm gì.</p></div><div><b>03</b><h3>Bằng chứng rời rạc</h3><p>Khó giải thích, đào tạo và kiểm soát chất lượng.</p></div></div></div><p className="story-quote">Bài toán không chỉ là ai nợ nhiều, mà là hôm nay nên ưu tiên ai, làm gì và vì sao.</p></section>
      <section className="story-section story-solution" id="solution"><SectionHeading eyebrow="02 · GIẢI PHÁP" title="Một Trợ lý giúp biến dữ liệu thành quyết định có căn cứ" children="Từ danh sách ưu tiên đến hành động, cán bộ có thể xem bằng chứng, mô phỏng và hỏi sâu trong cùng một câu chuyện." /><div className="solution-grid"><div className="solution-lead"><Zap size={26} /><b>AI Case Brief</b><h3>Hiểu nhanh tình trạng, bằng chứng, lý do và điều cần chú ý của một hồ sơ.</h3><p>Capability nổi bật giúp cán bộ bắt đầu đúng trước khi hỏi sâu hoặc mô phỏng.</p></div>{[['Danh sách ưu tiên','Xác định hồ sơ nên xử lý trước',Target],['Giải thích quyết định','Biết vì sao hệ thống đề xuất',MessageCircle],['Mô phỏng tình huống','Thử thay đổi bối cảnh an toàn',Sparkles],['Kiến thức có nguồn','Tra cứu quy trình nghiệp vụ',Database]].map(([title, text, Icon]) => <div className="solution-card" key={title as string}><Icon size={23} /><b>{title as string}</b><p>{text as string}</p></div>)}</div></section>
      <section className="story-section journey-section" id="journey"><SectionHeading eyebrow="03 · HÀNH TRÌNH NGƯỜI DÙNG" title="Từ trang giới thiệu đến hành động có căn cứ" children="Một hành trình thống nhất trên Web hoặc Zalo." /><StoryImage src="user-journey.png" alt="Infographic hành trình người dùng từ trang giới thiệu đến hành động" className="wide-image" /><p className="image-summary"><CheckCircle2 size={17} /> Mới: AI Case Brief giúp cán bộ hiểu nhanh hồ sơ trước khi hỏi sâu hoặc mô phỏng.</p></section>
      <section className="story-section brief-section" id="case-brief"><div><SectionHeading eyebrow="04 · TÓM TẮT AI CHO HỒ SƠ" title="Hiểu một hồ sơ trong vài chục giây" children="AI Case Brief tổng hợp thông tin khách hàng, quyết định hiện tại, điểm cơ hội thu hồi, dòng tiền, PTP, lịch sử liên hệ và kiến thức liên quan khi cần." /><p className="brief-agentbase"><Sparkles size={18} /> AgentBase giúp Trợ lý xác định đúng dữ liệu và công cụ cần dùng cho từng câu hỏi, thay vì phụ thuộc vào một kịch bản cố định.</p></div><div className="brief-card"><div className="brief-card-head"><span>TÓM TẮT AI CHO HỒ SƠ</span><button aria-label="Làm mới tóm tắt minh họa"><Sparkles size={15} /> Làm mới</button></div><h3>SYN002846</h3><div className="brief-metrics"><b>CALL<small>Tuyến xử lý</small></b><b>47/100<small>Điểm ưu tiên</small></b><b>Chờ tự thanh toán<small>Hành động hiện tại</small></b></div><div className="brief-detail"><b>TÌNH TRẠNG HIỆN TẠI</b><p>11 ngày quá hạn, tiền vào 7 ngày gần nhất là 48 triệu đồng và chưa có cam kết thanh toán.</p><b>VÌ SAO?</b><p>Dòng tiền gần đây cho thấy khả năng tự thanh toán; cần tiếp tục theo dõi theo bối cảnh hiện tại.</p><b>BẰNG CHỨNG QUAN TRỌNG</b><p>Tiền vào 7 ngày · Dòng tiền ròng 30 ngày · Lịch sử liên hệ</p><b>CÁN BỘ NÊN CHÚ Ý</b><p>Kiểm tra tín hiệu mới trước khi chuyển sang liên hệ.</p></div><div className="brief-card-actions"><a href="#case">Xem bằng chứng</a><a href="#channels">Hỏi thêm <ArrowRight size={14} /></a></div></div></section>
      <section className="story-section case-section" id="case"><div className="case-copy"><SectionHeading eyebrow="05 · TÌNH HUỐNG SYN002846" title="Thuộc tuyến gọi không có nghĩa hôm nay nhất thiết phải gọi" children="SYN002846 cho thấy sự khác nhau giữa tuyến xử lý và hành động phù hợp tại thời điểm hiện tại." /><div className="case-action"><span>Tuyến CALL — tuyến gọi</span><b>Chờ khách hàng tự thanh toán</b><small>Kênh hiện tại: Chưa cần liên hệ</small></div></div><div className="case-facts">{[['DPD','11 ngày'],['Tiền vào 7 ngày','48 triệu đồng'],['Dòng tiền ròng 30 ngày','168 triệu đồng'],['PTP','Chưa có'],['Điểm cơ hội thu hồi','47 / 100']].map(([l,v]) => <div key={l}><span>{l}</span><b>{v}</b></div>)}</div><p className="case-disclaimer">Điểm cơ hội thu hồi là điểm ưu tiên tương đối, không phải xác suất khách hàng sẽ thanh toán.</p></section>
      <section className="story-section simulation-section" id="simulation"><SectionHeading eyebrow="06 · MÔ PHỎNG WHAT-IF" title="Cùng một chính sách, bối cảnh thay đổi thì hành động có thể thay đổi" /><div className="sim-grid"><div><span>TRƯỚC</span><b>Tiền vào 7 ngày: 48 triệu</b><strong>Chờ khách hàng tự thanh toán</strong><small>Chưa cần liên hệ</small></div><ArrowRight /><div className="sim-after"><span>GIẢ ĐỊNH</span><b>Tiền vào 7 ngày: 0<br />Dòng tiền ròng 30 ngày: 0</b><strong>Liên hệ khách hàng</strong><small>Gọi điện</small></div></div><p className="disclaimer"><ShieldCheck size={16} /> Decision Core tính lại kết quả; AI chỉ giải thích trạng thái mới. Mô phỏng không thay đổi dữ liệu thật.</p></section>
      <section className="story-section channels-section" id="channels"><div className="channel-copy"><SectionHeading eyebrow="07 · WEB + ZALO" title="Xem sâu trên Web. Hỏi nhanh qua Zalo." children="Hai kênh khác nhau, cùng một Bộ máy quyết định." /><div className="channel-list"><div><span className="channel-icon web">W</span><p><b>Web</b><small>Danh sách ưu tiên, hồ sơ, AI Case Brief, bằng chứng, mô phỏng và Trợ lý.</small></p></div><div><span className="channel-icon zalo">Z</span><p><b>Zalo</b><small>Hỏi tự nhiên và theo dõi follow-up theo ngữ cảnh hồ sơ.</small></p></div></div><div className="chat-bubbles"><span>Tính điểm SYN002846</span><span>Nếu nó không có tiền vào tuần này thì sao?</span><span>Thế giờ làm gì?</span></div></div><StoryImage src="zalo-demo-live-context.png" alt="Demo Zalo với hồ sơ SYN002846 và ngữ cảnh mô phỏng" /></section>
      <section className="story-section demo-section" id="demo"><SectionHeading eyebrow="08 · HÀNH TRÌNH DEMO" title="Theo một hồ sơ từ dữ liệu đến hành động" children="Chọn một cảnh để xem lại câu chuyện demo. Dữ liệu đều là dữ liệu mô phỏng." /><DemoGallery /></section>
      <section className="story-section architecture-section" id="architecture"><SectionHeading eyebrow="09 · CÁCH AI HOẠT ĐỘNG" title="AI hiểu câu hỏi. Bộ máy nghiệp vụ quyết định." children="AgentBase chọn đúng dữ liệu và công cụ trong phạm vi được cho phép. GLM 5.2 tổng hợp và giải thích; Decision Core vẫn là nguồn duy nhất quyết định route, score, hành động và kênh." /><StoryImage src="system-architecture.png" alt="Infographic kiến trúc Web, Zalo, Decision Core và GreenNode" className="wide-image" /><div className="architecture-notes"><span>Cán bộ</span><span>AgentBase chọn dữ liệu / công cụ</span><span>GLM 5.2 tóm tắt / giải thích</span><span>Decision Core quyết định nghiệp vụ</span></div></section>
      <section className="story-section green-section" id="greennode"><div className="green-copy"><SectionHeading eyebrow="10 · GREENNODE TRONG SẢN PHẨM" title="GreenNode giúp Trợ lý hiểu đúng câu hỏi và dùng đúng công cụ" children="Decision Core quyết định đúng. GreenNode giúp cán bộ hiểu và khai thác quyết định đó nhanh hơn." /><div className="green-points"><div><b>AgentBase</b><span>Điều phối đúng công cụ và nguồn dữ liệu theo từng câu hỏi trong phạm vi được cho phép.</span></div><div><b>GreenNode MaaS + GLM 5.2</b><span>Tổng hợp và diễn giải dữ liệu, kết quả nghiệp vụ thành ngôn ngữ dễ hiểu cho cán bộ.</span></div><div><b>Vector Database + Qwen Flash</b><span>Tra cứu kiến thức nghiệp vụ có nguồn.</span></div><div><b>Local multilingual embedding</b><span>Nhúng ngôn ngữ đa ngôn ngữ chạy cục bộ, nằm ngoài GreenNode-hosted boundary.</span></div></div></div><StoryImage src="greennode-in-product.png" alt="GreenNode trong sản phẩm và ranh giới với Decision Core" /></section>
      <section className="story-section impact-section" id="impact"><SectionHeading eyebrow="11 · TÁC ĐỘNG + BẰNG CHỨNG" title="Ưu tiên tốt hơn có thể giảm thao tác không cần thiết" children="Các con số là ước tính theo giả định của bản demo, không phải ROI đã đạt." /><div className="impact-stats"><div><b>3.000</b><span>hồ sơ demo</span></div><div><b>1.740</b><span>thuộc tuyến CALL</span></div><div><b>32</b><span>CALL nhưng chưa cần gọi ngay</span></div><div><b>~1.065</b><span>giờ/năm</span></div><div><b>~106,5 triệu</b><span>đồng/năm</span></div></div><div className="parity-strip"><span><b>100%</b> Decision parity</span><span><b>100%</b> Score parity</span><span><b>0</b> Wrong CIF</span><span><b>0</b> Cross-CIF context leak</span><span><b>0</b> Unsupported decision claim</span></div><p className="disclaimer">AI Case Brief được kiểm soát để giữ nguyên kết quả Decision Core và không trộn dữ liệu giữa các hồ sơ. 32 hồ sơ không đồng nghĩa đã giảm được 32 cuộc gọi.</p></section>
      <section className="story-section roadmap-section" id="roadmap"><SectionHeading eyebrow="12 · LỘ TRÌNH + FAQ" title="Từ Hackathon đến pilot có thể đo lường" /><div className="roadmap-grid"><div><span>HIỆN TẠI</span><ul>{['Web','Zalo','Decision Core','Simulation','RAG','AI Case Brief','AgentBase bounded orchestration'].map(x => <li key={x}><CheckCircle2 size={16} />{x}</li>)}</ul></div><div><span>TIẾP THEO</span><ul>{['T24','DigiLenO','Contact Center','real-data shadow pilot','outcome measurement','officer feedback loop','AI-assisted call preparation'].map(x => <li key={x}><ArrowRight size={16} />{x}</li>)}</ul></div></div><div className="shadow-mode"><b>Shadow Mode Pilot</b><span>Vận hành hiện tại</span><ArrowRight size={17}/><span>Copilot chạy song song</span><ArrowRight size={17}/><span>So sánh recommendation với actual outcome</span></div><Faq /></section>
    </main><footer className="story-footer"><div className="story-shell footer-shell"><div><span className="story-kicker">13 · MSB AI Hackathon 2026</span><h2>Từ dữ liệu hôm nay đến <span>hành động hiệu quả hơn</span></h2><p>MSB Trợ lý Thu hồi Nợ giúp cán bộ ưu tiên đúng hồ sơ, hiểu rõ lý do và hành động có căn cứ.</p><a className="story-button story-button-primary" href="/login">Bắt đầu trải nghiệm <ArrowRight size={17} /></a></div><div className="footer-meta"><b>Nhóm thực hiện: Debt Radar</b><span>Powered by GreenNode AI</span><small>Dữ liệu mô phỏng · Không sử dụng dữ liệu khách hàng thật</small></div></div></footer>
  </div>;
}

export function LoginPage() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { fetch('/demo/auth/me', { credentials: 'include' }).then(r => { if (r.ok) window.location.replace('/app'); }); }, []);
  const submit = async (event: FormEvent) => {
    event.preventDefault(); if (busy) return; setBusy(true); setError('');
    try {
      const response = await fetch('/demo/auth/login', { method: 'POST', credentials: 'include', headers: {'Content-Type':'application/json'}, body: JSON.stringify({username, password}) });
      const body = await response.json();
      if (!response.ok) throw new Error(body?.error?.message || 'Không thể đăng nhập.');
      window.location.replace('/app');
    } catch (e: any) { setError(e.message || 'Không thể đăng nhập.'); setBusy(false); }
  };
  return <main className="login-page">
    <a className="login-brand" href="/"><span className="public-brand-mark">MSB</span><span><b>Trợ lý Thu hồi Nợ</b><small>Powered by GreenNode AI</small></span></a>
    <section className="login-card" aria-labelledby="login-title">
      <div className="login-icon"><ShieldCheck size={21}/></div><div className="eyebrow">KHU VỰC TÁC NGHIỆP</div>
      <h1 id="login-title">Đăng nhập hệ thống</h1><p>Truy cập Tổng quan, danh sách ưu tiên và hồ sơ khách hàng trong bản demo.</p>
      <form onSubmit={submit}><label>Tên đăng nhập<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required /></label><label>Mật khẩu<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required /></label>{error&&<p className="login-error" role="alert">{error}</p>}<button className="primary login-submit" disabled={busy}>{busy?<><LoaderCircle className="spin" size={16}/> Đang đăng nhập...</>:<>Đăng nhập <ArrowRight size={16}/></>}</button></form>
      <small className="login-disclaimer">Đây là quyền truy cập bản demo, không phải xác thực ngân hàng trong môi trường sản xuất.</small>
    </section>
    <footer className="login-footer">MSB · Powered by GreenNode AI · Dữ liệu mô phỏng</footer>
  </main>;
}

export function LogoutButton({logout}:{logout:()=>void}) { return <button className="logout-button" onClick={logout}><LogOut size={16}/> Đăng xuất</button>; }
